### PR TITLE
fix base64url padding

### PR DESCRIPTION
**Pull request by watahani**

### CODE REVIEW

**Comment by watahani** [comment]
($missingCharacters -lt 4) がそもそも要らないですね。削除します。

**Comment by juntakata** [comment]
Not sure but $missingCharacters will be either of 4, 3, 2, or 1 with your suggestion. So if($missingCharacters -gt 0) is always true and 4 unnecessary = will be added.

**Comment by watahani** [comment]
😂

it should be if($missingCharacters -ne 4) .

**Comment by juntakata** [comment]
Thanks for your contribution!

**Pull request merged**
